"""home destination migration - fix foreign key and constraints

Revision ID: d4e50caa5bbd
Revises: cedb736b352b
Create Date: 2025-06-30 12:16:36.530848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd4e50caa5bbd'
down_revision: Union[str, Sequence[str], None] = 'cedb736b352b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_cities_id'), ['id'], unique=False)

    with op.batch_alter_table('home_page_destinations', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('order',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('home_page_destinations_image_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'files', ['image'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_page_destinations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('home_page_destinations_image_fkey'), 'images', ['image'], ['id'])
        batch_op.alter_column('order',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=None,
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=None,
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cities_id'))
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
